### ISSUE TITLE
01 February 2023

### ISSUE THREAD

**Issue by ImSaMPro** [AIOCodeBase/GFGPOTD#650]
# **Task Lists**

- [x] #652
- [x] #653
- [x] #654
- [x] #655
- [ ] [C] Add C Solution for Problem Of The Day (_optional_)
- [ ] [C#] Add C# Solution for Problem Of The Day (_optional_)
- [ ] [JavaScript] Add JavaScript Solution for Problem Of The Day (_optional_)

<br />
<br />

### **How do I get assigned to these issues?**

*You must leave a comment with the issues you want assigned.*

### **Is there any limit to the number of issues that can be assigned?**

*Yes, one person can only be assigned two issues per day from the four (README, C++, Java, and Python 3).*

### **Can I be assigned to multiple issues on different days by commenting once?**

*Yes, you can be assigned to multiple issues on different days by commenting once. However, you must be assigned to the contributor role in order to do so. If you already have access to the contributor role, simply list the issue in a comment that you want to be assigned to.*

**Example:**
```
01 January 2023 - Java & Python
04 January 2023 - README.md & Java
12 January 2023 - C++
19 January 2023 - README.md
```

### **How do I get access to the Contributor role?**

*You must contribute 2-3 times before being granted access to the contributor role.*

### **Can I be assigned to issues that are optional?**

*If [C], [C#], or [JavaScript] are available for the problem of the day, you can be assigned to it on the day of the problem.*

**Comment by Rishav1707** [comment]
### Please assign the following issue to me:-

1 February 2023 - C++ & README
2 February 2023 - C++ & README
.
.
.
up to...

20 February 2023 - C++ & README

**Comment by ImSaMPro** [comment]
@Rishav1707 ,
That's great!

**Comment by Rishav1707** [comment]
> @Rishav1707 , That's great! Sure! But 1st Feb can't be assigned!

Then from 2 Feb 2023?

**Comment by ImSaMPro** [comment]
@Rishav1707 
From tomorrow onwards you can checkout this repo too https://github.com/AIOCodeBase/LCPOTD

**Comment by ImSaMPro** [comment]
> > @Rishav1707 , That's great! Sure! But 1st Feb can't be assigned!
> 
> Then from 2 Feb 2023?

yes! you can be assigned from 2nd feb!

**Comment by Rishav1707** [comment]
> @Rishav1707 From tomorrow onwards you can checkout this repo too https://github.com/AIOCodeBase/LCPOTD

ok sure!!
