### ISSUE TITLE
19 February 2023

### ISSUE THREAD

**Issue by ImSaMPro** [AIOCodeBase/GFGPOTD#674]
# **Task Lists**

- [ ] [README.md] Add a README.md for Problem Of The Day
- [ ] [C++] Add C++ Solution for Problem Of The Day
- [ ] [Java] Add Java Solution for Problem Of The Day
- [ ] [Python3] Add Python3 Solution for Problem Of The Day
- [ ] [C] Add C Solution for Problem Of The Day (_optional_)
- [ ] [C#] Add C# Solution for Problem Of The Day (_optional_)
- [ ] [JavaScript] Add JavaScript Solution for Problem Of The Day (_optional_)

<br />
<br />

### **How do I get assigned to these issues?**

*You must leave a comment with the issues you want assigned.*

### **Is there any limit to the number of issues that can be assigned?**

*Yes, one person can only be assigned two issues per day from the four (README, C++, Java, and Python 3).*

### **Can I be assigned to multiple issues on different days by commenting once?**

*Yes, you can be assigned to multiple issues on different days by commenting once. However, you must be assigned to the contributor role in order to do so. If you already have access to the contributor role, simply list the issue in a comment that you want to be assigned to.*

**Example:**
```
01 January 2023 - Java & Python
04 January 2023 - README.md & Java
12 January 2023 - C++
19 January 2023 - README.md
```

### **How do I get access to the Contributor role?**

*You must contribute 2-3 times before being granted access to the contributor role.*

### **Can I be assigned to issues that are optional?**

*If [C], [C#], or [JavaScript] are available for the problem of the day, you can be assigned to it on the day of the problem.*
